//// <auto-generated />
//using System;
//using CityApi.Data;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace CityApi.Migrations
//{
//    [DbContext(typeof(CityDBContext))]
//    [Migration("20230329132738_CityMigraton")]
//    partial class CityMigration
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "7.0.2")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("FirtsApi.Models.Apartment", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<int>("ApartmentNumber")
//                        .HasColumnType("int");

//                    b.Property<int>("Floor")
//                        .HasColumnType("int");

//                    b.Property<double>("FullArea")
//                        .HasColumnType("float");

//                    b.Property<Guid>("HomeId")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<double>("LivingArea")
//                        .HasColumnType("float");

//                    b.Property<int>("ResidentsQuantity")
//                        .HasColumnType("int");

//                    b.Property<int>("RoomsQuantity")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("HomeId");

//                    b.ToTable("Apartments");
//                });

//            modelBuilder.Entity("FirtsApi.Models.Home", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("City")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Country")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("HouseNumber")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("PostIndex")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Street")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Homes");
//                });

//            modelBuilder.Entity("FirtsApi.Models.Resident", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<Guid>("ApartmentId")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("DateOfBirth")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Email")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("PersonalCode")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("PhoneNumber")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Surname")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.HasIndex("ApartmentId");

//                    b.ToTable("Residents");
//                });

//            modelBuilder.Entity("FirtsApi.Models.User", b =>
//                {
//                    b.Property<long>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("bigint");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

//                    b.Property<string>("Access")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Login")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Password")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Users");
//                });

//            modelBuilder.Entity("FirtsApi.Models.Apartment", b =>
//                {
//                    b.HasOne("FirtsApi.Models.Home", "Home")
//                        .WithMany("Apartments")
//                        .HasForeignKey("HomeId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Home");
//                });

//            modelBuilder.Entity("FirtsApi.Models.Resident", b =>
//                {
//                    b.HasOne("FirtsApi.Models.Apartment", "Apartment")
//                        .WithMany("Residents")
//                        .HasForeignKey("ApartmentId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Apartment");
//                });

//            modelBuilder.Entity("FirtsApi.Models.Apartment", b =>
//                {
//                    b.Navigation("Residents");
//                });

//            modelBuilder.Entity("FirtsApi.Models.Home", b =>
//                {
//                    b.Navigation("Apartments");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
